### ISSUE TITLE
slurm MaxSubmitJobPerUser help needed !!! 

### ISSUE THREAD

**Issue by Navin-techi** [OleHolmNielsen/Slurm_tools#10]
Is there a way to restrict the user to submit a limited number of jobs for a particular partition is slurm ./ restrict user with maxjob and maxsubmitjobs per account in slurm using sacctmgr.

**Comment by OleHolmNielsen** [comment]
This sounds like a general Slurm question, perhaps you could ask the slurm-users mailing list.
