### ISSUE TITLE
How to install the tools if I am not the superuser?

### ISSUE THREAD

**Issue by Ordgod** [OleHolmNielsen/Slurm_tools#11]
I think this is very useful tool, but I am just a normal user on a cluster. I want to know how to install the tools by myself? 

I can not use `sodu` command.
I can not copy files to `/etc/` or to `/user/bin/` because of permission limitation.

-------------
I solved this problem by myself.
I edited the pestat file directoly to set the path, 
and then I put this pestat file in my home directory,
and then I put this line in my bashrc file `PATH=/home/myusername/bin:"$PATH" `

**Comment by OleHolmNielsen** [comment]
I agree that you can copy the pestat to $HOME/bin and then it should work, if you have set the PATH as you suggest.
