### ISSUE TITLE
Some issues with Scripts.....

### ISSUE THREAD

**Issue by Zhexue-M** [OleHolmNielsen/Slurm_tools#15]
Hello together,

I had a "problem" regarding your SLURM - Tools and I can't find the mistake so far. I've got the following output, if I called the script (showuserjobs):

awk: not an option: --version
awk: line 11: regular expression compile failed (missing operand)
*
Batch job status for cluster influxus-physicus at Thu 30 Sep 2021 12:32:40 PM CEST

Job summary: 0 jobs total (max=10000) in all partitions.
 
Username/              Runnin         Limit Pendin        
Totals      Account      Jobs   CPUs   CPUs   Jobs   CPUs Further info
=========== ========== ====== ====== ====== ====== ====== =============================
awk: line 37: syntax error at or near [
awk: line 59: syntax error at or near [
awk: line 60: syntax error at or near [
awk: line 61: syntax error at or near [
awk: line 64: syntax error at or near [

I think, this is very simple for you, but I search for a while, why it doesn't work....
Thank you in advances.....

Z. Matthias

**Comment by OleHolmNielsen** [comment]
It seems that your system runs an old AWK version.  These lines in teh script checks the version:

# WARNING: GNU gawk version 4.0 or later is required for arrays of arrays
awk_version=`awk --version ...

Even on CentOS 6 the awk --version works correctly.

Can you determine your awk version?

**Comment by Zhexue-M** [comment]
Hello again and thank you for your quick response.

Yes, this was true. On my system was an OLD - AWK installed. Now, I had installed the newest GNU awk on my cluster and modify your script with "module load ...", so that I can use the newest awk on the whole cluster.

Thanks so lot, now it's work....
Best regards

Z. Matthias
