### ISSUE TITLE
tag a release?

### ISSUE THREAD

**Issue by alexmyczko** [OleHolmNielsen/Slurm_tools#19]
Hi Ole

Wouldn't it be great to tag a release?

Best,

**Comment by OleHolmNielsen** [comment]
Hi Alex,
I agree with your comment.  However, pestat is just one of a number of commands in my repository, and it doesn't make sense to wrap them all up under a single release.  I don't know if pestat can be tagged as a release independently of the other tools?
Thanks,
Ole

**Comment by alexmyczko** [comment]
i was not asking for pestat but the whole repo/tools be released as tar.gz with version number?
