### ISSUE TITLE
Need some mentoring re slurm admin in HPC

### ISSUE THREAD

**Issue by rvencu** [OleHolmNielsen/Slurm_tools#22]
Hi, we are willing to build some AI HPC Cluster infrastructure for grants to researchers running open-source projects in AI field.

I am responsible to build up the cluster(s) and setup shop to deliver the compute grants to recipients. At this moment we were able to [script the clusters launching](https://github.com/Stability-AI/1click-hpc) (using AWS cloud) and we have to dive into slurm, accounting, quotas, qos and user management.

Looking at this repo I understand all these are already optimized on your end. We would like to achieve something similar in the near future and I was wondering for any kind of help we can get (from basic interactions here up to mentoring or even contracted services - not in charge with purchasing but if that is the correct way I could ask for it)

Please let me know what are our chances for that. Thanks

**Comment by OleHolmNielsen** [comment]
Hi, I apologize that I don't have the time to provide consulting services.
