### ISSUE TITLE
Incompatibilities between Dash and Bash

### ISSUE THREAD

**Issue by mtds** [OleHolmNielsen/Slurm_tools#6]
Hi.

I have troubles from time to time in running your scripts on Debian/Ubuntu machines.

The problem is related to the (in)famous switch of the ``/bin/sh`` symlink to ``/bin/dash`` instead of ``/bin/bash``.

References:
* [Dash as /bin/sh](https://wiki.ubuntu.com/DashAsBinSh)
* [Bug report: Script that are using bash could be broken with the new symlink](https://bugs.launchpad.net/ubuntu/+source/dash/+bug/61463)

I guess you are running the 'Slurm Tools' scripts on RHEL/CentOS, where ``/bin/sh``
still points to Bash. 

Would it be possible for you to consider switching the shabang prompt from ``#!/bin/sh`` to ``#!/usr/bin/env bash``?

**Comment by OleHolmNielsen** [comment]
Sure, this makes sense. I've updated all my scripts now.

I found a discussion on https://stackoverflow.com/questions/21612980/why-is-usr-bin-env-bash-superior-to-bin-bash/
