### ISSUE TITLE
awk error using slurmusersettings and not defined group/account

### ISSUE THREAD

**Issue by perfettp** [OleHolmNielsen/Slurm_tools#9]
Hi, 
  I'm facing an error using `slurmusersettings` to add my users while ignoring the primary group (`export ignore_primary_groups=1`). 

My overall idea is to select users to add to the cluster using only the secondary groups (as all my users has primary group `USERGROUP` which is not meaningful in this context). 

My `accounts.conf` is defined like this (and SlurmDBD is consistent):
```
institute::1:all users
dep1:institute:1:Dep1
dep2:institute:1:Dep 2
```

When I run `slurmusersettings`, when the script manage a `USERNAME` with primary gid `USERGROUP` this error occours (`debug=1`):
 ```
...
User USERNAME group USERGROUP
### User USERNAME exists under account= fairshare=
### NOTICE: Group USERGROUP has no settings, assuming default values for user USERNAME
gawk: cmd. line:344: (FILENAME=- FNR=40) fatal: attempt to use a scalar value as array
...
```
`USERGROUP` account  is intentionally not defined in SlurbDBD and `USERNAME` does not belongs to any other defined group/account.

I fixed (for me?) this issue with commit 7e42c73

The modified version returns a command like
```
/usr/bin/sacctmgr -i create user name=USERNAME
```
which then fail (no defaultaccount defined) which is for me an acceptable behavior  (I'm also working on a second patch to not exclude users based on the primary group and there this behavior will be fixed I hope) 

Thank you for your scripts and your documentation! They're very useful, nicely written and your documentation is precious!
In a cluster with LDAP users/groups (obtained via `getent`) we are evaluating to use `slurmaccounts` and `slurmusersettings` to manage accounting because of their simplicity (plain shell/awk scripting rulez!).

Cheers, Paolo

**Comment by OleHolmNielsen** [comment]
Hi Paolo,
I'm glad that you like the Slurm accounts tool.  We use it all the time to administer Slurm users and accounts.
Thanks a lot for fixing this bug.  It is obvious that one should check that setting[u][config] is an array, but this didn't hit us so far. 
I have committed your change now. My tests show that the patch is working fine in our environment.
Best regards,
Ole
